services:
  product:
    build: microservices/product-service
    hostname: product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql30:
        condition: service_healthy

  api:
    build: api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - product

  mysql30:
    image: mysql:5.7
    platform: linux/amd64
    #mem_limit: 350m
    ports:
      - "3320:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=product-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql30:/var/lib/mysql30
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
